export const Services = [
  {
    id: 1,
    header: 'EQUIPAJE EXTRA',
    description:
      'Select the services for each of your flights by clicking on the flight segment and passenger where you want your service added. The total amounts will be updated as you make your selection.',
    serviceType: 'PerFlightAndPassenger',
    singleSelectionForIncludedServices: false,
    controlType: 'buttons',
    confirm: false,
    confirmText: '',
    hideForBookingCreate: false,
    hideForManageBooking: false,
    showPriceInOption: false,
    passengerTypes: ['ADT', 'CHD'],
    noSelectionOption: false,
    translationCodeForNoSelection: '',
    comment: false,
    options: [
      {
        id: 1,
        name: 'HAND BAGGAGE',
        description: 'HAND BAGGAGE',
        code: 'HAND',
        icon: '',
        preSelected: false,
        preSelectedFor: [],
        maxQuantity: 1,
        allowedFareTypes: [],
        hideForOneWay: false,
        hideForMultipleFlights: false,
        displayForEquipmentTypeGroups: [],
        hideForEquipmentTypeGroups: [],
      },
      {
        id: 2,
        name: 'Extra bag 1',
        description: 'Extra bag 1',
        code: 'BAG',
        icon: '',
        preSelected: false,
        preSelectedFor: [],
        maxQuantity: 1,
        allowedFareTypes: [],
        hideForOneWay: false,
        hideForMultipleFlights: false,
        displayForEquipmentTypeGroups: [],
        hideForEquipmentTypeGroups: [],
      },
      {
        id: 3,
        name: 'Extra bag 2',
        description: 'BAG2',
        code: 'BAG2',
        icon: '',
        preSelected: false,
        preSelectedFor: [],
        maxQuantity: 1,
        allowedFareTypes: [],
        hideForOneWay: false,
        hideForMultipleFlights: false,
        displayForEquipmentTypeGroups: [],
        hideForEquipmentTypeGroups: [],
      },
      {
        id: 4,
        name: 'Extra bag 3',
        description: 'BAG3',
        code: 'BAG3',
        icon: '',
        preSelected: false,
        preSelectedFor: [],
        maxQuantity: 1,
        allowedFareTypes: [],
        hideForOneWay: false,
        hideForMultipleFlights: false,
        displayForEquipmentTypeGroups: [],
        hideForEquipmentTypeGroups: [],
      },
    ],
  },
  {
    id: 2,
    header: 'EQUIPAJE ESPECIAL',
    description: '',
    serviceType: 'PerFlightAndPassenger',
    singleSelectionForIncludedServices: false,
    controlType: 'buttons',
    hideForBookingCreate: false,
    hideForManageBooking: false,
    showPriceInOption: false,
    passengerTypes: ['ADT', 'CHD'],
    noSelectionOption: false,
    translationCodeForNoSelection: '',
    comment: false,
    options: [
      {
        id: 1,
        name: 'Equipaje Especial',
        description: 'SPORTS EQUIPMENT',
        code: 'SPEQ',
        icon: '',
        preSelected: false,
        preSelectedFor: [],
        maxQuantity: 1,
        allowedFareTypes: [],
        hideForOneWay: false,
        hideForMultipleFlights: false,
        displayForEquipmentTypeGroups: [],
        hideForEquipmentTypeGroups: [],
      },
    ],
  },
  {
    id: 3,
    header: 'PRIORITY CHECK IN',
    description: 'Priority check in',
    serviceType: 'PerFlightAndPassenger',
    singleSelectionForIncludedServices: false,
    controlType: 'buttons',
    confirm: false,
    confirmText: '',
    hideForBookingCreate: false,
    hideForManageBooking: false,
    showPriceInOption: false,
    passengerTypes: ['ADT', 'CHD', 'INF'],
    noSelectionOption: false,
    translationCodeForNoSelection: '',
    comment: false,
    options: [
      {
        id: 1,
        name: 'Priority check in',
        description: 'Priority check in',
        code: 'XCKI',
        icon: '',
        preSelected: false,
        preSelectedFor: [],
        maxQuantity: 1,
        allowedFareTypes: [],
        hideForOneWay: false,
        hideForMultipleFlights: false,
        displayForEquipmentTypeGroups: [],
        hideForEquipmentTypeGroups: [],
      },
    ],
  },
  {
    id: 4,
    header: 'FAST TRACK',
    description: 'FAST TRACK',
    serviceType: 'PerFlightAndPassenger',
    singleSelectionForIncludedServices: false,
    controlType: 'buttons',
    confirm: false,
    confirmText: '',
    hideForBookingCreate: false,
    hideForManageBooking: false,
    showPriceInOption: false,
    passengerTypes: ['ADT', 'CHD', 'INF'],
    noSelectionOption: false,
    translationCodeForNoSelection: '',
    comment: false,
    options: [
      {
        id: 1,
        name: 'Fast Track',
        description: 'Fast Track',
        code: 'FTRK',
        icon: '',
        preSelected: false,
        preSelectedFor: [],
        maxQuantity: 1,
        allowedFareTypes: [],
        hideForOneWay: false,
        hideForMultipleFlights: false,
        displayForEquipmentTypeGroups: [],
        hideForEquipmentTypeGroups: [],
      },
    ],
  },
  {
    id: 5,
    header: 'MENUS PREMIUM',
    description: '',
    serviceType: 'PerFlightAndPassenger',
    singleSelectionForIncludedServices: false,
    controlType: 'buttons',
    confirm: false,
    confirmText: '',
    hideForBookingCreate: false,
    hideForManageBooking: false,
    showPriceInOption: false,
    passengerTypes: ['ADT', 'CHD', 'INF'],
    noSelectionOption: false,
    translationCodeForNoSelection: '',
    comment: false,
    options: [
      {
        id: 1,
        name: 'Menú Sapori di Italia (opción pasta-vegetariano)',
        description: 'Menú Sapori di Italia (opción pasta-vegetariano)',
        code: 'PAUM',
        icon: 'https://images.prismic.io/evelop-ezycommerce/bd0ad859-ec09-4745-ae57-170b9c9c8215_menu+pasta+cenital.jpeg?auto=compress,format',
        preSelected: false,
        preSelectedFor: [],
        maxQuantity: 1,
        allowedFareTypes: [],
        hideForOneWay: false,
        hideForMultipleFlights: false,
        displayForEquipmentTypeGroups: [],
        hideForEquipmentTypeGroups: [],
      },
      {
        id: 2,
        name: 'Menú Made in USA (opción hamburguesa Angus)',
        description: 'Menú Made in USA (opción hamburguesa Angus)',
        code: 'HAUM',
        icon: 'https://images.prismic.io/evelop-ezycommerce/4e24c194-33fb-46c4-a26e-2662f1624b34_EVELOP_2020_MENU_HAMBURGUESA_470x313.jpg',
        preSelected: false,
        preSelectedFor: [],
        maxQuantity: 1,
        allowedFareTypes: [],
        hideForOneWay: false,
        hideForMultipleFlights: false,
        displayForEquipmentTypeGroups: [],
        hideForEquipmentTypeGroups: [],
      },
      {
        id: 3,
        name: 'Menú España (opción pescado)',
        description: 'Menú España (opción pescado)',
        code: 'FIUM',
        icon: 'https://images.prismic.io/evelop-ezycommerce/5651ddfa-5134-474c-94a0-d134b794cc61_menu+pescado+cenital.jpeg?auto=compress,format',
        preSelected: false,
        preSelectedFor: [],
        maxQuantity: 1,
        allowedFareTypes: [],
        hideForOneWay: false,
        hideForMultipleFlights: false,
        displayForEquipmentTypeGroups: [],
        hideForEquipmentTypeGroups: [],
      },
      {
        id: 4,
        name: 'Menú Made in USA (opción solomillo)',
        description: 'Menú Made in USA (opción solomillo)',
        code: 'MEUM',
        icon: 'https://images.prismic.io/evelop-ezycommerce/4805a028-1955-499c-9d97-103c6e050060_menu+carne+cenital.jpeg?auto=compress,format',
        preSelected: false,
        preSelectedFor: [],
        maxQuantity: 1,
        allowedFareTypes: [],
        hideForOneWay: false,
        hideForMultipleFlights: false,
        displayForEquipmentTypeGroups: [],
        hideForEquipmentTypeGroups: [],
      },
      {
        id: 5,
        name: 'Menú Healthy & Tasty (opción pollo)',
        description: 'Menú Healthy & Tasty (opción pollo)',
        code: 'LIUM',
        icon: 'https://images.prismic.io/evelop-ezycommerce/a7469a9e-132a-4980-a13f-6533d7685b87_menu%CC%81+light+cenital.jpeg?auto=compress,format',
        preSelected: false,
        preSelectedFor: [],
        maxQuantity: 1,
        allowedFareTypes: [],
        hideForOneWay: false,
        hideForMultipleFlights: false,
        displayForEquipmentTypeGroups: [],
        hideForEquipmentTypeGroups: [],
      },
    ],
  },
  {
    id: 7,
    header: 'MENUS INFANTIL',
    description: '',
    serviceType: 'PerFlightAndPassenger',
    singleSelectionForIncludedServices: false,
    controlType: 'buttons',
    confirm: false,
    confirmText: '',
    hideForBookingCreate: false,
    hideForManageBooking: false,
    showPriceInOption: false,
    passengerTypes: ['CHD'],
    noSelectionOption: false,
    translationCodeForNoSelection: '',
    comment: false,
    options: [
      {
        id: 1,
        name: 'Children menu',
        description: 'Children menu',
        code: 'CHML',
        icon: '',
        preSelected: false,
        preSelectedFor: [],
        maxQuantity: 1,
        allowedFareTypes: [],
        hideForOneWay: false,
        hideForMultipleFlights: false,
        displayForEquipmentTypeGroups: [],
        hideForEquipmentTypeGroups: [],
      },
    ],
  },
  {
    id: 8,
    header: 'SEGUROS',
    description: '',
    serviceType: 'PerPassenger',
    singleSelectionForIncludedServices: false,
    controlType: 'buttons',
    confirm: false,
    confirmText: '',
    hideForBookingCreate: false,
    hideForManageBooking: false,
    showPriceInOption: false,
    passengerTypes: ['ADT', 'INF', 'CHD'],
    noSelectionOption: false,
    translationCodeForNoSelection: '',
    comment: false,
    options: [
      {
        id: 1,
        name: 'Seguro de asistencia médica',
        description: 'Seguro de asistencia médica',
        code: 'SAV1',
        icon: '',
        preSelected: false,
        preSelectedFor: [],
        maxQuantity: 1,
        allowedFareTypes: [],
        hideForOneWay: false,
        hideForMultipleFlights: false,
        displayForEquipmentTypeGroups: [],
        hideForEquipmentTypeGroups: [],
      },
      {
        id: 2,
        name: 'Seguro de asistencia + anulación',
        description: 'Seguro de asistencia + anulación',
        code: 'SAV2',
        icon: '',
        preSelected: false,
        preSelectedFor: [],
        maxQuantity: 1,
        allowedFareTypes: [],
        hideForOneWay: false,
        hideForMultipleFlights: false,
        displayForEquipmentTypeGroups: [],
        hideForEquipmentTypeGroups: [],
      },
      {
        id: 3,
        name: 'Seguro de asistencia médica PT',
        description: 'Seguro de asistencia médica PT',
        code: 'SAV3',
        icon: '',
        preSelected: false,
        preSelectedFor: [],
        maxQuantity: 1,
        allowedFareTypes: [],
        hideForOneWay: false,
        hideForMultipleFlights: false,
        displayForEquipmentTypeGroups: [],
        hideForEquipmentTypeGroups: [],
      },
      {
        id: 4,
        name: 'Seguro de asistencia + anulación PT',
        description: '',
        code: 'SAV4',
        icon: '',
        preSelected: false,
        preSelectedFor: [],
        maxQuantity: 1,
        allowedFareTypes: [],
        hideForOneWay: false,
        hideForMultipleFlights: false,
        displayForEquipmentTypeGroups: [],
        hideForEquipmentTypeGroups: [],
      },
    ],
  },
  {
    id: 9,
    header: 'REQUERIMIENTOS ESPECIALES',
    description: '',
    serviceType: 'PerFlightAndPassenger',
    singleSelectionForIncludedServices: false,
    controlType: 'buttons',
    confirm: false,
    confirmText: '',
    hideForBookingCreate: false,
    hideForManageBooking: false,
    showPriceInOption: false,
    passengerTypes: ['ADT', 'INF', 'CHD'],
    noSelectionOption: false,
    translationCodeForNoSelection: '',
    comment: false,
    options: [
      {
        id: 1,
        name: 'Comida sin azúcar',
        description: '',
        code: 'DBML',
        icon: '',
        preSelected: false,
        preSelectedFor: [],
        maxQuantity: 1,
        allowedFareTypes: [],
        hideForOneWay: false,
        hideForMultipleFlights: false,
        displayForEquipmentTypeGroups: [],
        hideForEquipmentTypeGroups: [],
      },
      {
        id: 2,
        name: 'Comida sin glúten',
        description: '',
        code: 'GFML',
        icon: '',
        preSelected: false,
        preSelectedFor: [],
        maxQuantity: 1,
        allowedFareTypes: [],
        hideForOneWay: false,
        hideForMultipleFlights: false,
        displayForEquipmentTypeGroups: [],
        hideForEquipmentTypeGroups: [],
      },
      {
        id: 3,
        name: 'Comida baja en calorías',
        description: '',
        code: 'LCML',
        icon: '',
        preSelected: false,
        preSelectedFor: [],
        maxQuantity: 1,
        allowedFareTypes: [],
        hideForOneWay: false,
        hideForMultipleFlights: false,
        displayForEquipmentTypeGroups: [],
        hideForEquipmentTypeGroups: [],
      },
      {
        id: 4,
        name: 'Comida baja en colesterol, grasa',
        description: '',
        code: 'LFML',
        icon: '',
        preSelected: false,
        preSelectedFor: [],
        maxQuantity: 1,
        allowedFareTypes: [],
        hideForOneWay: false,
        hideForMultipleFlights: false,
        displayForEquipmentTypeGroups: [],
        hideForEquipmentTypeGroups: [],
      },
      {
        id: 5,
        name: 'Comida sin lactosa',
        description: '',
        code: 'NLML',
        icon: '',
        preSelected: false,
        preSelectedFor: [],
        maxQuantity: 1,
        allowedFareTypes: [],
        hideForOneWay: false,
        hideForMultipleFlights: false,
        displayForEquipmentTypeGroups: [],
        hideForEquipmentTypeGroups: [],
      },
      {
        id: 6,
        name: 'Comida baja en sodio',
        description: '',
        code: 'LSML',
        icon: '',
        preSelected: false,
        preSelectedFor: [],
        maxQuantity: 0,
        allowedFareTypes: [],
        hideForOneWay: false,
        hideForMultipleFlights: false,
        displayForEquipmentTypeGroups: [],
        hideForEquipmentTypeGroups: [],
      },
      {
        id: 7,
        name: 'Comida vegetariana',
        description: '',
        code: 'VGML',
        icon: '',
        preSelected: false,
        preSelectedFor: [],
        maxQuantity: 1,
        allowedFareTypes: [],
        hideForOneWay: false,
        hideForMultipleFlights: false,
        displayForEquipmentTypeGroups: [],
        hideForEquipmentTypeGroups: [],
      },
      {
        id: 8,
        name: 'Comida vegetariana lacto-ovo',
        description: '',
        code: 'VLML',
        icon: '',
        preSelected: false,
        preSelectedFor: [],
        maxQuantity: 1,
        allowedFareTypes: [],
        hideForOneWay: false,
        hideForMultipleFlights: false,
        displayForEquipmentTypeGroups: [],
        hideForEquipmentTypeGroups: [],
      },
      {
        id: 9,
        name: 'Comida halal',
        description: '',
        code: 'MOML',
        icon: '',
        preSelected: false,
        preSelectedFor: [],
        maxQuantity: 1,
        allowedFareTypes: [],
        hideForOneWay: false,
        hideForMultipleFlights: false,
        displayForEquipmentTypeGroups: [],
        hideForEquipmentTypeGroups: [],
      },
      {
        id: 10,
        name: 'Comida niños',
        description: '',
        code: 'CHML',
        icon: '',
        preSelected: false,
        preSelectedFor: [],
        maxQuantity: 1,
        allowedFareTypes: [],
        hideForOneWay: false,
        hideForMultipleFlights: false,
        displayForEquipmentTypeGroups: [],
        hideForEquipmentTypeGroups: [],
      },
      {
        id: 11,
        name: 'Comida bebés',
        description: '',
        code: 'BBML',
        icon: '',
        preSelected: false,
        preSelectedFor: [],
        maxQuantity: 1,
        allowedFareTypes: [],
        hideForOneWay: false,
        hideForMultipleFlights: false,
        displayForEquipmentTypeGroups: [],
        hideForEquipmentTypeGroups: [],
      },
    ],
  },
  {
    id: 10,
    header: 'TT+',
    description: 'TT+ test',
    serviceType: 'PerFlightAndPassenger',
    singleSelectionForIncludedServices: false,
    controlType: 'buttons',
    confirm: false,
    confirmText: '',
    hideForBookingCreate: true,
    hideForManageBooking: true,
    showPriceInOption: false,
    passengerTypes: ['ADT', 'CHD', 'INF'],
    noSelectionOption: false,
    translationCodeForNoSelection: '',
    comment: false,
    options: [
      {
        id: 1,
        name: 'turista plus test',
        description: 'turista plus test',
        code: 'TT+',
        icon: '',
        preSelected: false,
        preSelectedFor: [],
        maxQuantity: 0,
        allowedFareTypes: [],
        hideForOneWay: false,
        hideForMultipleFlights: false,
        displayForEquipmentTypeGroups: [],
        hideForEquipmentTypeGroups: [],
      },
    ],
  },
  {
    id: 11,
    header: 'EQUIPAJE DEPORTIVO',
    description: 'Descr equipaje deportivo',
    serviceType: 'PerFlightAndPassenger',
    singleSelectionForIncludedServices: false,
    controlType: 'buttons',
    confirm: false,
    confirmText: '',
    hideForBookingCreate: false,
    hideForManageBooking: false,
    showPriceInOption: false,
    passengerTypes: ['ADT', 'CHD'],
    noSelectionOption: false,
    translationCodeForNoSelection: '',
    comment: false,
    options: [
      {
        id: 1,
        name: 'Tabla de surf',
        description: 'Descr tabla de surf',
        code: 'SPEB',
        icon: '',
        preSelected: false,
        preSelectedFor: [],
        maxQuantity: 1,
        allowedFareTypes: [],
        hideForOneWay: false,
        hideForMultipleFlights: false,
        displayForEquipmentTypeGroups: [],
        hideForEquipmentTypeGroups: [],
      },
      {
        id: 2,
        name: 'Bicicleta',
        description: 'Desc Bicicleta',
        code: 'BIKE',
        icon: '',
        preSelected: false,
        preSelectedFor: [],
        maxQuantity: 1,
        allowedFareTypes: [],
        hideForOneWay: false,
        hideForMultipleFlights: false,
        displayForEquipmentTypeGroups: [],
        hideForEquipmentTypeGroups: [],
      },
    ],
  },
  {
    id: 12,
    header: 'Equipajes Voluminosos',
    description: 'Descr Equipajes voluminosos',
    serviceType: 'PerFlightAndPassenger',
    singleSelectionForIncludedServices: false,
    controlType: 'buttons',
    confirm: false,
    confirmText: '',
    hideForBookingCreate: false,
    hideForManageBooking: false,
    showPriceInOption: false,
    passengerTypes: ['ADT', 'CHD'],
    noSelectionOption: false,
    translationCodeForNoSelection: '',
    comment: false,
    options: [
      {
        id: 1,
        name: 'Voluminoso',
        description: 'Eq. Voluminoso',
        code: 'VOL',
        icon: '',
        preSelected: false,
        preSelectedFor: [],
        maxQuantity: 1,
        allowedFareTypes: [],
        hideForOneWay: false,
        hideForMultipleFlights: false,
        displayForEquipmentTypeGroups: [],
        hideForEquipmentTypeGroups: [],
      },
    ],
  },
];
