version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SERVER_PORT=${SERVER_PORT}
        - TYPEORM_USERNAME=${TYPEORM_USERNAME}
        - TYPEORM_PASSWORD=${TYPEORM_PASSWORD}
        - TYPEORM_DATABASE=${TYPEORM_DATABASE}
        - TYPEORM_HOST=${TYPEORM_HOST}
        - TYPEORM_PORT=${TYPEORM_PORT}
        - TYPEORM_SYNCHRONIZE=${TYPEORM_SYNCHRONIZE}
        - TYPEORM_DROP_SCHEMA=${TYPEORM_DROP_SCHEMA}
        - TYPEORM_RUN_MIGRATION=${TYPEORM_RUN_MIGRATION}
        - TYPEORM_LOG=${TYPEORM_LOG}
    container_name: app