environmentData:
  ALLOWED_PAYMENT_IP: '35.195.204.5,35.234.68.27'
  BASE_URL: 'https://api.iberojet.eu'
  BTN_BOARDING_PASS_ENABLED: 'false'
  BTN_CHECKIN_ENABLED: 'false'
  BTN_CHECKIN_TEMPORAL: 'true'
  CACHE_SERVER_HOST: 'redis-backend'
  CACHE_SERVER_PORT: '6379'
  CACHE_SERVER_TTL: '600'
  CHANNEL: 'MOBILE'
  CHANNEL_WEB: 'WEB'
  DB_ADMIN_GUEST_PORT: '80'
  DB_ADMIN_HOST_PORT: '8081'
  DB_ADMIN_MAIL: 'admin@admin.com'
  DB_INIT_DB: 'postgres'
  EPG_URL: 'https://checkout.easypaymentgateway.com'
  FIREBASE_APPID_WEB: '1:951295815345:web:b6bab87c0cfb752dbbbc90'
  FIREBASE_AUTHDOMAIN_WEB: 'iberojet-digittal.firebaseapp.com'
  FIREBASE_CLIENTEMAIL: 'firebase-adminsdk-vcuyj@iberojet-digittal.iam.gserviceaccount.com'
  FIREBASE_DATABASEURL_WEB: 'https://iberojet-digittal-default-rtdb.firebaseio.com'
  FIREBASE_MEASUREMENT_ID_WEB: 'G-JW8PLRXWD9'
  FIREBASE_MESSAGINGSENDERID_WEB: '951295815345'
  FIREBASE_PROJECTID_WEB: 'iberojet-digittal'
  FIREBASE_STORAGEBUCKET_WEB: 'iberojet-digittal.appspot.com'
  HOME_VIDEO_LINK: 'https://digittal.es/iberojet/home.mp4'
  IBERO_JET_IMAGE_VERSION: '0.0.1'
  MERCHANT_ID: '10478'
  MINIMUM_ANDROID_VERSION: '1.1.4'
  MINIMUM_DESIRABLE_ANDROID_VERSION: '1.1.4'
  MINIMUM_DESIRABLE_IOS_VERSION: '1.1.3'
  MINIMUM_IOS_VERSION: '1.1.3'
  OPERATION_TYPE: 'DEBIT'
  PAYMENT_SOLUTION: 'creditcards'
  PRISMIC_REPO_NAME: 'https://evelop-ezycommerce.cdn.prismic.io/api/v2'
  PRODUCT_ID: '104780001'
  RADIXX_URL: 'https://eve.app.radixxhost.com/EVE'
  RADIXX_USERNAME: 'MOBAPP_E9_P'
  RADIXX_WEB_USERNAME: 'VELOP_E9_P'
  RATE_LIMIT_WINDOWS_MAX_PER_HOURS: '800'
  RATE_LIMIT_WINDOWS_MAX_PER_MINUTES: '120'
  RATE_LIMIT_WINDOWS_MAX_PER_SECONDS: '20'
  RATE_LIMIT_WINDOWS_MS_PER_HOURS: '3600000'
  RATE_LIMIT_WINDOWS_MS_PER_MINUTES: '60000'
  RATE_LIMIT_WINDOWS_MS_PER_SECONDS: '1000'
  SENTINEL_HOST: 'redis-backend'
  SENTINEL_NAME: 'mymaster'
  SENTINEL_PORT: '26379'
  SENTRY_DNS: 'https://8f7c6a3cc6eb4ccd8730ab98c0dd5561@o4505438095802368.ingest.sentry.io/4505438254071808'
  SERVER_JWT_EXPIRATION_TIME: '2100'
  SERVER_PORT: '3000'
  SERVICING: 'false'
  SHOW_SWAGGER: 'true'
  TAG: 'prod'
  TERMS_CONDITIONS: 'CONDICIONES TEST'
  TYPEORM_DATABASE: 'iberojetdb'
  TYPEORM_DROP_SCHEMA: 'false'
  TYPEORM_HOST: 'localhost'
  TYPEORM_LOG: 'false'
  TYPEORM_PORT: '5432'
  TYPEORM_RUN_MIGRATION: 'true'
  TYPEORM_SYNCHRONIZE: 'false'
  TYPEORM_USERNAME: 'templateuser'

secretEnvironmentData:
  #Env imported from secret iberojet-backend-dev/iberojet-api-pro
  CACHE_SERVER_PASSWORD: SW5zdGFuYS1MZWUtTWV0cmljYXM=
  DB_ADMIN_PASS: YWRtaW4=
  EPG_MERCHANT_PASSWORD: MDhkZDBkN2MyMDJiZWIyNWE5YmY5ZDBkNmJkYjg4N2I=
  FIREBASE_APIKEY_WEB: QUl6YVN5QXhXcy16TmQyOW1acFVsNXRRbDVuM3E3Wnptc1hGdF9v
  FIREBASE_PRIVATEKEY: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktjd2dnU2pBZ0VBQW9JQkFRQ2VDSXJtejk4Ykh1d1QKSVA3Z2NobitRRCtDbWpjVFB5aHJtcDZBV2JWQS9MejZoeFVOcy9Jc2tjS0c5SS9KRThTVzVZcDdaMHI1OWVoUgpUcDBNczJpWnBUS1lkQ3hIbEpwTGVNTHJ6VVRIaGxYZUlhNHRIbWxGMnY0QnZPdWhmYnIrTkg1Q3RTbGJ4YzV4CnZXM3hrbXE2aC9YRXpIYnRFQUppREJ4T2k3WlFRbStuTlVVcy9WY2pybHNoc3liZWI1YTlHRjh5eHBVa1dxazIKZjdNNkZkWmM2Y2hFbjJldkQ4MmZIeHFlVmJXUm90dk9Bc0RwS1E0bDBSLyt2MFdPMGxOWkYxUjFtYnFTSlRPMApGRm1GdFBGWnRIdmJPUytOZnRSK1hPWFVCN0I1ZHA1N2xEM2YvZnVRTmIzTTJldDJuaDh1QmptblhGQVZiNnc5CnNnOHI1aFBoQWdNQkFBRUNnZ0VBRW54SlV5cHBuSkNIYU0xcFF2UFYyb25GWkErSjliUmpsQUtvRzdkaW5sRnkKQVpRZmdGVFdOU1J2cnIyWXZCcVYybGpMVkJnSEN5b2FuTGduWXI3eHMxZEJqZGU0L2o2QnRlWlFWcWpTTE15bgo2cTNoNCtFMHl6a01rVU42QkkvaWVhM0dQeU5WelNoY042M0MySWtaOXV2RWNkckE1b1lDNFZrdFRuckZQcW4zCmZSVXhLOEVYMGhnd2pLaWFXZyswRmF0bmhIUmJHZlFkcGUrbEtuUmV1QSsrQVlzQU9OL2ZxSFE1U1Q2d2VYYkkKODRXVmsxOEVzWVYvVEFsZndCTnRUWXAvSkF2Zy9FbVhPK1ZpUzQ5Mk4zM09ZclVBQ3B5VWZqZHBUN3YrdHA2Ugo0WUFSeTlJcDRyM2RQekM1UlRuMFlBak5yckpJRWlMb2hJSG04NVIxeVFLQmdRRGVvbFJ3VEZaREcraEdFRGpVCmowNzNVcHJDVkhla2xvRFRKQUtDNnBDNSs5YngwK3E0WU1SeGhIZlNGcGY1bDFuQlFLb2tFeXJoSlJIeURrZlAKQTM4Z2VnSkdUQk53RGFvOEVlNDhxR21INTd4a0c2VW40NG1BbmJIay9BTTR2VjlMVWZGaWgwZ2JIYSs3QTlGRApFd3JhK0NNSGxoVVpVdjgrZm1iVjIrM21kd0tCZ1FDMXQ3Y0RkdG5hQkxOK1hZTG5TcmV4ZUVRaWxXRXdEejhJCnNqUW05UGhxVG83TGNheUxZTG1LK29nOFFrZ3lNQ1JLR0dHNTIySUZ0cHJ6Nm03cjE5TkF1eWdpVUcyY21Fd1oKQzNRZGdETWJ2UW5jMHVhT01GRGJrS2lkVzR3SWd2RzB6aEltV29QY3JVNCtNUmRWK1VZam5qMEpFM3ZBTWpYVgpXd2ZKSUFqMlp3S0JnQTBGWDN6bDZoR291ekFGMk4wTnVLZWNiREs3Yi9mdldYOS8xcW5EZ0Uxd1hrVHNpUWpaCm1BT3ZwTFpqM2VXYUpZUzQvSHA1cUlOY2dLMHdpcUNmNnJxQ2lFbUdQNGpKTTlDcGw4NXlaeUdzdXdiNzJ1LzMKVGQ1NDJxT3kzWmxlOGdqY3RRcDNNUTlzOEE4M0RQRW9WdlV4bUJMa2d6MWs3a3JBWjlGUU9KekhBb0dCQUxXMgpTNVYwUU83cDZvKy9kTXBUQmhPNmZ1L1NUc2hmUnBvc2tVZ3ZpVVhNM3JBRU1SV0RHS2NvVmhsajhvdjFaaVNOCjh4T0dsS08vOFgxZC9hTnJRLzJqNmNNK2lBMmlvZDRkZlBTUElReG80YmJuVXRQMjdyUlJHTHVhTXhMRDFtNEYKNzFKWkN5a2VTSEthWm9wN1phN3lhbmhyK2tDOE5PYndTMzNNd2dtYkFvR0FQdDBXdlZZeVMraWx5aTR0akJBRwpWK0xPTlg4TXA5Znl5bEhRZkJGcVdTeTc1SHYwM0ZkUkx4eU4wcEhOUVFUTEJWRVRZWWc0dGZqUUo0UkZKVnlECkVKWnRaQXVBSkFnbzNHWXFhNVkvK2FEa3VZSEZoOUkwTXRBbUN5Yld5WXMzUnVtVmlNRVF6U21WbWdNc1NEVngKN24vZDJKcW1YQUVJT21ZOU1kVFR2Ymc9Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
  PRISMIC_ACCESS_TOKEN: TUM1Wk9YRlVkSGhGUVVGRFNVRm5kbE5rLjc3LTk3Ny05NzctOUxDcGM3Ny05NzctOTc3LTk3Ny05NzctOTc3LTlWalp6NzctOTc3LTk3Ny05NzctOTc3LTlYRTQ0QmUtdmUtdlJ2dnY3M3Z2NzN2djcwaDc3LTk=
  RADIXX_PASSWORD: S0VTRiRCUkVYIQ==
  RADIXX_WEB_PASSWORD: QkVKWSREUkxZIQ==
  SERVER_JWT_SECRET: VG9wc2V5Q3JldA==
  TYPEORM_PASSWORD: dGVtcGxhdGV1c2VyMTIz