apiVersion: v2
name: app
description: A Helm chart for Kubernetes
type: application
version: 0.0.0

dependencies:
  - name: generic-app
    version: 0.0.17
    repository: https://moreirodamian.github.io/helm-charts/