apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: #{NAME}#-#{ENV}#
  namespace: #{NAME}#-#{ENV}#
  labels:
    site: #{NAME}#-#{ENV}#
spec:
  maxReplicas: #{MAX_REPLICAS}#
  minReplicas: #{MIN_REPLICAS}#
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: #{NAME}#-#{ENV}#
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
---
