ingressPublic:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "X-Robots-Tag: noindex, nofollow, nosnippet, noarchive";
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
  hosts:
    - host: "pre-backend-iberojet.ingress-public.ocppre.aws-pre.avoristravel.io"
      paths: [ "/" ]
  ingressClass: nginx-public

ingressPublicAdvanced:
  - name: api-dev-iberojet-eu
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-http
      kubernetes.io/tls-acme: 'true'
      nginx.ingress.kubernetes.io/configuration-snippet: |
        more_set_headers "X-Robots-Tag: noindex, nofollow, nosnippet, noarchive";
      nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    hosts:
      - host: "api.dev.iberojet.eu"
        paths: [ "/" ]
    ingressClass: nginx-public
    tls:
      - hosts:
          - "api.dev.iberojet.eu"
        customSecretName: tls-api-dev-iberojet-eu