export interface Config {
  FIREBASE_APIKEY_WEB: string;
  FIREBASE_AUTHDOMAIN_WEB: string;
  FIREBASE_PROJECTID_WEB: string;
  FIREBASE_STORAGEBUCKET_WEB: string;
  FIREBASE_MESSAGINGSENDERID_WEB: string;
  FIREBASE_APPID_WEB: string;
  FIREBASE_DATABASE_URL_WEB: string;
}
