ingressPublic:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "X-Robots-Tag: noindex, nofollow, nosnippet, noarchive";
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
  hosts:
    - host: "stg-backend-iberojet.ingress-public.ocppro.aws-pro.avoristravel.io"
      paths: [ "/" ]
  ingressClass: nginx-public
