environmentData:
  ALLOWED_PAYMENT_IP: '34.98.116.22,35.246.248.42,35.189.207.233'
  BASE_URL: 'https://api.dev.iberojet.eu'
  BTN_BOARDING_PASS_ENABLED: 'false'
  BTN_CHECKIN_ENABLED: 'false'
  BTN_CHECKIN_TEMPORAL: 'false'
  CACHE_SERVER_HOST: 'pre-redis-backend'
  CACHE_SERVER_PORT: '6379'
  CACHE_SERVER_TTL: '600'
  CHANNEL: 'MOBILE'
  CHANNEL_WEB: 'WEB'
  DB_ADMIN_GUEST_PORT: '80'
  DB_ADMIN_HOST_PORT: '8081'
  DB_ADMIN_MAIL: 'admin@admin.com'
  DB_INIT_DB: 'postgres'
  EPG_URL: 'https://checkout-stg.easypaymentgateway.com'
  FIREBASE_APPID_WEB: '1:156022916841:web:08ede0cc0e0336b7465278'
  FIREBASE_AUTHDOMAIN_WEB: 'iberojet-digittal-dev.firebaseapp.com'
  FIREBASE_CLIENTEMAIL: 'firebase-adminsdk-awwt8@iberojet-digittal-dev.iam.gserviceaccount.com'
  FIREBASE_DATABASEURL_WEB: 'https://iberojet-c560a-default-rtdb.firebaseio.com'
  FIREBASE_MEASUREMENT_ID_WEB: 'G-8PG46C9MBZ'
  FIREBASE_MESSAGINGSENDERID_WEB: '156022916841'
  FIREBASE_PROJECTID_WEB: 'iberojet-digittal-dev'
  FIREBASE_STORAGEBUCKET_WEB: 'iberojet-digittal-dev.appspot.com'
  HOME_VIDEO_LINK: 'https://digittal.es/iberojet/home.mp4'
  IBERO_JET_IMAGE_VERSION: '0.0.1'
  MERCHANT_ID: '10478'
  MINIMUM_ANDROID_VERSION: '1.1.2'
  MINIMUM_DESIRABLE_ANDROID_VERSION: '1.1.2'
  MINIMUM_DESIRABLE_IOS_VERSION: '1.1.0'
  MINIMUM_IOS_VERSION: '1.1.0'
  OPERATION_TYPE: 'DEBIT'
  PAYMENT_SOLUTION: 'creditcards'
  PRISMIC_REPO_NAME: 'https://evelop-ezycommerce.cdn.prismic.io/api/v2'
  PRODUCT_ID: '104780001'
  RADIXX_GO_API_DOMAIN: 'api-staging.radixxgo.com'
  RADIXX_GO_API_USERNAME: 'eomobileapiuser'
  RADIXX_GO_API_VERSION: '1.8'
  RADIXX_URL: 'https://eveappuat3.radixxuat.com/EVE'
  RADIXX_USERNAME: 'MOBAPP_E9_U'
  RADIXX_WEB_USERNAME: 'VELOP_E9_U'
  RATE_LIMIT_WINDOWS_MAX_PER_HOURS: '8000000'
  RATE_LIMIT_WINDOWS_MAX_PER_MINUTES: '1200000'
  RATE_LIMIT_WINDOWS_MAX_PER_SECONDS: '800000'
  RATE_LIMIT_WINDOWS_MS_PER_HOURS: '3600000'
  RATE_LIMIT_WINDOWS_MS_PER_MINUTES: '60000'
  RATE_LIMIT_WINDOWS_MS_PER_SECONDS: '1000'
  SENTINEL_HOST: 'pre-redis-backend'
  SENTINEL_NAME: 'mymaster'
  SENTINEL_PORT: '26379'
  SENTRY_DNS: 'https://8f7c6a3cc6eb4ccd8730ab98c0dd5561@o4505438095802368.ingest.sentry.io/4505438254071808'
  SERVER_JWT_EXPIRATION_TIME: '2100'
  SERVER_PORT: '3000'
  SERVICING: 'false'
  SHOW_SWAGGER: 'true'
  TAG: 'tst'
  TERMS_CONDITIONS: 'CONDICIONES TEST'
  TYPEORM_DATABASE: 'iberojetdb'
  TYPEORM_DROP_SCHEMA: 'false'
  TYPEORM_HOST: 'localhost'
  TYPEORM_LOG: 'false'
  TYPEORM_PORT: '5432'
  TYPEORM_RUN_MIGRATION: 'true'
  TYPEORM_SYNCHRONIZE: 'false'
  TYPEORM_USERNAME: 'templateuser'

secretEnvironmentData:
  #Env imported from secret iberojet-backend-dev/iberojet-api-dev
  CACHE_SERVER_PASSWORD: SW5zdGFuYS1MZWUtTWV0cmljYXM=
  DB_ADMIN_PASS: YWRtaW4=
  EPG_MERCHANT_PASSWORD: ZGI4NDI4MmI0ZGMwNjc2MTQ4NDNiYTAzY2Y4YWI0Mzk=
  FIREBASE_APIKEY_WEB: QUl6YVN5QU1kRUM3UHZyUTAyNUYwNG5kYlNVQlhNWTJOQlRqV1dj
  FIREBASE_PRIVATEKEY: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktjd2dnU2pBZ0VBQW9JQkFRQ2U2TFFsQUJxdjhYQVYKc1hmNU01NGo1QkVLRWRNWEVUREJZYjk5VmVZN3RhQlJtaUYrb245M2RLdm5yNi93b3NlTFJwRkkzcnpyRm80MgpSeStPcTl5eHJjSy84OHFtU0d1WGo2diszZlJuNUNJd2FWeWw3TFlEYnpabUwrWER2cFlCSkNTVmRzWDUxUUdJCkF6Z2xZandzajNMckVBbWJ4azJjeTQwUUJTcm04bkRYWnVpZ3A0WC9Ld1RzSTlqT3JTNU5CSGI4eTV1UGJGczYKUW9OSkEzR3pQc3JFWCttSVJzRGJqMkNwTElUZWZuTUZhVzhuS2xnUmxmRTZ0Z0wyYWV6Z1B4UGtGTnJBRDVVVQp5eEUxZmtWblRjM3ZTczNUSkxsTlZGNitwTzY0SG1WNUZkd0xwSUlNNDJzYmNnR0R4ZElVNEZtaCtTRkpsMzNQCk9YblJmSWZEQWdNQkFBRUNnZ0VBT1FlS256ektWeHB1LzFvUmxIM1I0MCtXVGViWHV3K1FUOWFrd25aeGlqeEUKclFTRHdNN1FzQzVQQTNjcHpWS2VDbjNvNWg0Sjd0VEpkUEZYUC95dDE1Wmtyajd3RzMwaUgrS1A5NGZ3anRodwo3SzdqY1NqaXFaamdEUXhqaVR4ODJTdi9kU1NMS0g0cGJvYTVQN0ZocHh4VVFjZ2ZxcWdnY29VYXV3VWZ3SUh3CjVDaHQ2Ry9oYnVONHpNOTUwRms5T1BvRllqSlNOeWF2NEpVbmVKSmNZWG5IdmRCcEhHZFVHVTZaR1ZDL2wvS3AKWCs0VmVzcnFsR1hzdkNBVEMyRHBKWXVHdUNvTjhxdkRZRVVSd1FKTmVNSlpMZmVWdDNEVXk3RVZ6MHdMUGNLZwowRFVVRDRDbVdLRnVrRm9YTGwwdE1JSjBkUmVtU0FSNHFlRytOUUMvQVFLQmdRRFFacHRjU2lFamtkQ25GUHR2ClpSY1pjeDVra2xGdGFQQ1NTa0Z3emVLU0hPRHc5NE9sWHpxVXRjT2xwSUY4VERHVHlrSUlQQkIxVTZNNnRxUDIKcjVUelp1OWp3NWNzTW9zcW1YakNiZWVOZlFoNFFaYUVvVUdQaFlqMFQwS0dQTyt0bVJKUXpDWktPalFSVXVTQwppeXNOMEpGSXl1MlJLOEtVS2piUmFva3N2d0tCZ1FERE5FT0R5NVBjV0diU1YvQkRjeUdhRFRHcnRYT3dUNmo4CndVYitJVldXT29YT0RLOUNvSzcvTmNuSjZMSnN5WHN1Y09LTjFNNC9ESHZ1T0xMTUVLRGF3TlgvZjc0TStrRk4KY1NFQVdKeDdYV0srci9XNTRWdmp6MlNtcjh5eTZSZ1lKaUhNcmEyeWYxdFZEOXdoTDhNM3dOUnBEVCtDaVZiUwpKdnltRUpWeC9RS0JnUUM2RzBlV3pXUjJ2VnNXT3JpbnJDRkt5dkZUWXc5d280eGpPQWprMGhnSjM5eEpsT0J0CnFITktKbUJINW5iMEo1OEdtbE1KdzRuM0hPL2lHUVNuNGZra3ZNSC8xOFdDNU1nL0RMczQ5cWtZUTVaeXZpL0sKMWE4VW1tM0pyNVo3QnFRTDVXemoxc3hDOFdOYUxTcUFJZ1FhM0MxQ1VtYUJoQkRKL0VEa0Z6M1ZSUUtCZ0dQVApWMitQN1dheXdxcHhGRXE2RndYOEYxbXphcDFRcjUvS2k2NnNoMk5UUEZnNlBtcDVWK1Rsc2ZNU2tDUjRDUW1mCjZ3d1ROd0loTlVPSE5WQ01kR1pLVldYYkF1c0tFOWt4c0duSDV3WmpwSHJWNjNrS21YNXY4ZzRZT3p1SFhxNEMKMmlnYzdZWXFBU0FJQTAvcGFCRWNDTVJNWlIweGRQZjF2aUNDdkpwVkFvR0FZa0Y4WXhrTGRpSkN2bXVUTHFNaApKWDRib1dIaXZpZk12UTdtRlBXV0l5VitMazlTM3ZYY3dneEROajdMbXowVUJSSmJMakdQVmMwNUhKRHBiNU5QCmpkNXpFNm5Hbm96S3grZmRubWNFWmd1R3RRZ2U5dUxXelp3bkxKNndpU1VJSlpDU3lOcFd3L3JDVmZKNURWdFMKNU1DWmJIWXIrUEcxSmQ4WlRRaWZzS3c9Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
  PRISMIC_ACCESS_TOKEN: TUM1Wk9YRlVkSGhGUVVGRFNVRm5kbE5rLjc3LTk3Ny05NzctOUxDcGM3Ny05NzctOTc3LTk3Ny05NzctOTc3LTlWalp6NzctOTc3LTk3Ny05NzctOTc3LTlYRTQ0QmUtdmUtdlJ2dnY3M3Z2NzN2djcwaDc3LTk=
  RADIXX_GO_API_KEY: S3VoWXdudE5WaDcyZWs2RGljR1BzWUI0cjFxVnhPUzFmQlJCdjZ6NA==
  RADIXX_GO_API_PASSWORD: QjNLVjhTTGRuRmpIZUxidQ==
  RADIXX_PASSWORD: RFJFViRXRVNDIQ==
  RADIXX_WEB_PASSWORD: QUxPSyREUkVLIQ==
  SERVER_JWT_SECRET: VG9wc2V5Q3JldA==
  TYPEORM_PASSWORD: dGVtcGxhdGV1c2VyMTIz